# -*- coding: UTF-8 -*-

# 姑且算是一个夹具文件

# 主发行帐号私钥
SEED='SBRYFNS7O4RPXZR3VRZAIXQJNISHSJQHBG5SXDTU6LP2V7SMDRL4ZPT4'
# 连接的服务器，测试服务器随意填写，主服务器填写：PUBLIC或者MAIN，必须先在测试服务器上测试通过才能在主服务器上运行
API_SERVER='test'

# 所有资产的发行账户：
ISSUER_ADDRESS='GBGP4NT7S52HTW6EZI3RM3YKAAHEBQNBMMPQALNUJWUURQPX5AKCG3CI'
# 所有资产的分发账户：
DISTRIBUTOR_ADDRESS='GAFRGA77FLN4JIWG7P7TXUDS5RX2475V5CTVKQJOFMXKBE5AJ25I6HRA'
